# Site settings
baseurl = "/"
languageCode = "en-us"
title = "gogopr.org website"
theme = "ggp"
# Enter your tracking code to enable Google Analytics
googleAnalytics = "UA-XXXXXXXX-Y"

contentdir = "content"
datadir = "data"
layoutdir = "layouts"
publishdir = "public"

[params]
    # Meta
    title = "gogopr.org"
    subtitle = "gogoprog's games portfolio."
    author = "Gauthier Billot"
    nickname = "gogoprog"
    description = "gogopr.org"
    keywords = "gogoprog, portfolio, linux, game"

    # Body background color
	bodybgcolor = "#c9c9c9"

    # Footer text
    footertext = "Made using [Hugo](http://gohugo.io)"

    github = "https://github.com/gogoprog"
