name = "Ggp"
license = "MIT License" #original Codrops Lisense is here http://tympanus.net/codrops/licensing/
licenselink = "//github.com/aerohub/hugrid/blob/master/LICENSE.md"
description = "Made for gogopr.org"
tags = ["responsive", "grid", "portfolio", "cards", "simple", "collections", "google analytics"]
min_version = 0.15

[author]
  name = "Gauthier <gogoprog> Billot"

[orignal2]
  name = "Pavel Kanyshev"
  homepage = "//github.com/aerohub/hugrid"

[original]
  name = "Codrops' Thumbnail Grid with Expanding Preview"
  homepage = "http://tympanus.net/codrops/2013/03/19/thumbnail-grid-with-expanding-preview/"
  repo = "//github.com/codrops/ThumbnailGridExpandingPreview"
